[[games]]
name = "Blaspehmous 2"
path = "/home/moritz/Games/SteamLibrary/steamapps/compatdata/2114740/pfx/drive_c/users/steamuser/AppData/LocalLow/The Game Kitchen/Blasphemous 2/SteamUser_76561198017647090/Savegames/"
# comment = 

[[games]]
name = "Shadow Gambit: The Cursed Crew"
path = "/home/moritz/.var/app/com.usebottles.bottles/data/bottles/bottles/GOG-Galaxy/drive_c/users/moritz/AppData/Local/ShadowGambit_TCC/user_gog/"
comment = "Installed via Bottles"
